// generated by devtools/generate-template.go. DO NOT EDIT

package templates

import (
  "html/template"
  "log"

"github.com/bctnry/gitus/pkg/gitlib"
"strings"

)

	 type BranchSingleFileTemplateModel struct {
	 RepoName string
	 RepoDescription string
	 TypeStr string
	 NodeName string
	 CommitId string
	 AuthorInfo gitlib.AuthorTime
	 CommitterInfo gitlib.AuthorTime
	 CommitMessage string
	 CommitSignature string
	 Annotated bool
	 TaggerInfo gitlib.AuthorTime
	 TagMessage string
	 TagSignature string
	 TreePath string
	 FileContent string
	 FileLineNumber int
	 TreePathSegmentList []struct{
	 Name string
	 RelPath string
	 }
	 }

	 
	 type BranchTemplateModel struct {
	 RepoName string
	 RepoDescription string
	 TypeStr string
	 NodeName string
	 CommitId string
	 AuthorInfo gitlib.AuthorTime
	 CommitterInfo gitlib.AuthorTime
	 CommitMessage string
	 CommitSignature string
	 Annotated bool
	 TaggerInfo gitlib.AuthorTime
	 TagMessage string
	 TagSignature string
	 TreePath string
	 FileList []gitlib.TreeObjectItem
	 TreePathSegmentList []struct{
	 Name string
	 RelPath string
	 }
	 }

	 
	 type CommitHistoryItemModel struct {
	 ShortId string
	 Id string
	 Message string
	 AuthorInfo gitlib.AuthorTime
	 CommitterInfo gitlib.AuthorTime
	 }
	 
	 type CommitHistoryModel struct {
	 RepoName string
	 RepoDescription string
	 TypeStr string
	 NodeName string
	 CommitHistory []CommitHistoryItemModel
	 }

	 	 
	 type IndexModel struct {
	     RepositoryList []struct{RelPath string; Description string}
	 }

	 type InternalErrorModel struct{
	 ErrorCode int
	 ErrorMessage string
	 }
type RepositoryModel struct{
	RepoName string
	RepoObj gitlib.LocalGitRepository
	BranchList map[string]*gitlib.Branch
	TagList map[string]*gitlib.Tag
}

func LoadTemplate() *template.Template {
  var err error = nil
  masterTemplate := template.New("").Funcs(template.FuncMap{
"strjoin": strings.Join,

  })
  _, err = masterTemplate.New("_footer").Parse(`{{define "_footer"}}
<div class="footer-message">
Powered by Gitus.
</div>
{{end}}

`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("branch-single-file").Parse(`
{{$repoName :=.RepoName}}
{{$nodeName := .NodeName}}
{{$treePath := .TreePath}}
{{$typeStr := .TypeStr}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
	<link rel="stylesheet" href="/static/style.css">
	<title>{{$typeStr}}:{{$nodeName}} @ {{.RepoName}} :: Gitus</title>
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / REPOSITORY</div>
      <h1 class="repo-header-name" style="margin-bottom: 0"><a href="/repo/{{.RepoName}}">{{.RepoName}}</a></h1>
	  <div class="repo-header-branch">@{{$typeStr}}:<a href="/repo/{{.RepoName}}/{{$typeStr}}/{{$nodeName}}">{{if eq $typeStr "commit"}}{{slice $nodeName 0 8}}...{{else}}{{$nodeName}}{{end}}</a></div>
	</div>
	
	<div class="repo-description">{{.RepoDescription}}</div>
	
	<div class="repo-branch-description">
	  <div class="repo-branch-commit">
		<b>Commit</b> <code><a href="/repo/{{.RepoName}}/commit/{{.CommitId}}">{{.CommitId}}</a></code> (<a href="/repo/{{.RepoName}}/history/{{$typeStr}}:{{$nodeName}}">Full History</a>)<br />
		<b>Author</b>:
		<span class="author-name">{{.AuthorInfo.AuthorName}}</span>
		(<span class="author-email"><a href="mailto:{{.AuthorInfo.AuthorEmail}}">{{.AuthorInfo.AuthorEmail}}</a></span>)
		at <span class="author-time">{{.AuthorInfo.Time}}</span><br />
		<b>Committer</b>: 
		<span class="committer-name">{{.CommitterInfo.AuthorName}}</span>
		(<span class="committer-email"><a href="mailto:{{.CommitterInfo.AuthorEmail}}">{{.CommitterInfo.AuthorEmail}}</a></span>)
		at <span class="committer-time">{{.CommitterInfo.Time}}</span><br />
		<b>Message</b>:<br /><pre>{{.CommitMessage}}</pre>
		{{if gt (len .CommitSignature) 0}}
		<details><summary><b>Commit Signature</b></summary><pre>{{.CommitSignature}}</pre></details>
		{{end}}
	  </div>
	  
	  {{if eq $typeStr "tag"}}
	  <div class="repo-branch-tag">
		{{if .Annotated}}
		<b>Tagger</b>: 
		<span class="committer-name">{{.TaggerInfo.AuthorName}}</span>
		(<span class="committer-email"><a href="mailto:{{.TaggerInfo.AuthorEmail}}">{{.TaggerInfo.AuthorEmail}}</a></span>)
		at <span class="committer-time">{{.TaggerInfo.Time}}</span><br />
		<b>Tag Message</b>:<br /><pre>{{.TagMessage}}</pre>
		{{if gt (len .TagSignature) 0 }}
		<details><summary><b>Tag Signature</b></summary><pre>{{.TagSignature}}</pre></details>
		{{end}}
		{{else}}
		This is a lightweight tag with no extra annotation.
		{{end}}
	  </div>
	  {{end}}
	</div>
	<hr />

	<div class="tree-path-segment">
	  <a class="tree-path-segment-head" href="/repo/{{.RepoName}}/{{$typeStr}}/{{$nodeName}}">{{.RepoName}}@{{$typeStr}}:{{$nodeName}}</a>
	  
	  {{if gt (len .TreePathSegmentList) 0}}
	  {{range .TreePathSegmentList}}
	  / <a class="tree-path-segment-item" href="/repo/{{$repoName}}/{{$typeStr}}/{{$nodeName}}/{{.RelPath}}">{{.Name}}</a>
	  {{end}}
	  {{end}}
	</div>
	<div class="file-source-view">
	  <div class="file-source-line-number-panel">
		{{range .FileLineNumber}}
		<a id="L{{.}}" class="file-source-line-number-item" href="#L{{.}}">{{.}}</a>
		{{end}}
	  </div>
	  <pre class="file-content">{{.FileContent}}</pre>
	</div>

	<hr />
	<footer>
	  <a href="/repo/{{.RepoName}}">Back (Repository)</a>
	  <a href="/">Back (Depot)</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>

`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("branch").Parse(`
{{$repoName :=.RepoName}}
{{$nodeName := .NodeName}}
{{$treePath := .TreePath}}
{{$typeStr := .TypeStr}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
	<link rel="stylesheet" href="/static/style.css">
	<title>{{$typeStr}}:{{$nodeName}} @ {{.RepoName}} :: Gitus</title>
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / REPOSITORY</div>
      <h1 class="repo-header-name" style="margin-bottom: 0"><a href="/repo/{{.RepoName}}">{{.RepoName}}</a></h1>
	  <div class="repo-header-branch">@{{$typeStr}}:<a href="/repo/{{.RepoName}}/{{$typeStr}}/{{$nodeName}}">{{if eq $typeStr "commit"}}{{slice $nodeName 0 8}}...{{else}}{{$nodeName}}{{end}}</a></div>
	</div>
	<div class="repo-description">{{.RepoDescription}}</div>
	<div class="repo-branch-description">
	  <div class="repo-branch-commit">
		<b>Commit</b> <a href="/repo/{{.RepoName}}/commit/{{.CommitId}}">{{.CommitId}}</a> (<a href="/repo/{{.RepoName}}/history/{{$typeStr}}:{{$nodeName}}">Full History</a>)<br />
		<b>Author</b>:
		<span class="author-name">{{.AuthorInfo.AuthorName}}</span>
		(<span class="author-email"><a href="mailto:{{.AuthorInfo.AuthorEmail}}">{{.AuthorInfo.AuthorEmail}}</a></span>)
		at <span class="author-time">{{.AuthorInfo.Time}}</span><br />
		<b>Committer</b>: 
		<span class="committer-name">{{.CommitterInfo.AuthorName}}</span>
		(<span class="committer-email"><a href="mailto:{{.CommitterInfo.AuthorEmail}}">{{.CommitterInfo.AuthorEmail}}</a></span>)
		at <span class="committer-time">{{.CommitterInfo.Time}}</span><br />
		<b>Message</b>:<br /><pre>{{.CommitMessage}}</pre>
		{{if gt (len .CommitSignature) 0}}
		<details><summary><b>Commit Signature</b></summary><pre>{{.CommitSignature}}</pre></details>
		{{end}}
	  </div>
	  {{if eq $typeStr "tag"}}
	  <div class="repo-branch-tag">
		{{if .Annotated}}
		<b>Tagger</b>: 
		<span class="committer-name">{{.TaggerInfo.AuthorName}}</span>
		(<span class="committer-email"><a href="mailto:{{.TaggerInfo.AuthorEmail}}">{{.TaggerInfo.AuthorEmail}}</a></span>)
		at <span class="committer-time">{{.TaggerInfo.Time}}</span><br />
		<b>Tag Message</b>:<br /><pre>{{.TagMessage}}</pre>
		{{if gt (len .TagSignature) 0 }}
		<details><summary><b>Tag Signature</b></summary><pre>{{.TagSignature}}</pre></details>
		{{end}}
		{{else}}
		This is a lightweight tag with no extra annotation.
		{{end}}
	  </div>
	  {{end}}
	</div>
	
	<hr />
	
	<div class="tree-path-segment">
	  <span class="tree-path-segment-head"><a href="/repo/{{.RepoName}}/{{$typeStr}}/{{$nodeName}}">{{.RepoName}}@{{$typeStr}}:{{$nodeName}}</a></span>
	  {{if gt (len .TreePathSegmentList) 0}}
	  {{range .TreePathSegmentList}}
	  / <span class="tree-path-segment-item"><a href="/repo/{{$repoName}}/{{$typeStr}}/{{$nodeName}}/{{.RelPath}}">{{.Name}}</a></span>
	  {{end}}
	  {{end}}
	</div>

	<div class="file-list">
	  {{if gt (len .TreePath) 0}}
	  <div class="file-list-item"><a href="..">..</a></div>
	  {{end}}
	  
	  {{range .FileList}}
	  <div class="file-list-item">
		<svg class="file-list-item-icon">
		  {{if or (eq (.Mode) 100644) (eq (.Mode) 100755)}}
		  <use href="/static/assets/icons.svg#file"></use>
		  {{else if (eq (.Mode) 40000) }}
		  <use href="/static/assets/icons.svg#folder"></use>
		{{end}}
		</svg>
		<a href="/repo/{{$repoName}}/{{$typeStr}}/{{$nodeName}}/{{$treePath}}/{{.Name}}">{{.Name}}</a></div>
	  {{end}}
	</div>
	<hr />
	<footer>
	  <a href="/repo/{{.RepoName}}">Back (Repository)</a>
	  <a href="/">Back (Depot)</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>

`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("commit-history").Parse(`{{$repoName := .RepoName}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
	<link rel="stylesheet" href="/static/style.css">
	<title>history of {{.TypeStr}}:{{.NodeName}} @ {{.RepoName}} :: Gitus</title>
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / REPOSITORY</div>
      <h1 class="repo-header-name" style="margin-bottom: 0">{{.RepoName}}</h1>
	  <div class="repo-header-branch">History @ <a href="/repo/{{.RepoName}}/{{.TypeStr}}/{{.NodeName}}">{{.TypeStr}}:{{.NodeName}}</a></div>
	</div>
	
	<div class="repo-description">{{.RepoDescription}}</div>
	
	<hr />

	<div class="commit-history-container">
	  {{range .CommitHistory}}
	  <div class="commit-history-item">
		<div class="commit-history-item-id">
		  <span class="commit-history-item-short-id">{{.ShortId}}</span>
		  <span class="commit-history-item-id"><a href="/repo/{{$repoName}}/commit/{{.Id}}">{{.Id}}</a></span>
		</div>
		<div class="commit-history-item-author-info">
		  <b>Author</b>: {{.AuthorInfo.AuthorName}} (<a href="mailto:{{.AuthorInfo.AuthorEmail}}">{{.AuthorInfo.AuthorEmail}}</a>) at {{.AuthorInfo.Time}}<br />
		  <b>Committer</b>: {{.CommitterInfo.AuthorName}} (<a href="mailto:{{.AuthorInfo.AuthorEmail}}">{{.CommitterInfo.AuthorEmail}}</a>) at {{.CommitterInfo.Time}}<br />
		</div>
		<div class="commit-history-item-message">{{.Message}}</div>
	  </div>
	  {{end}}
	</div>
	<hr />
	<footer>
	  <a href="/repo/{{.RepoName}}/{{.TypeStr}}/{{.NodeName}}">Back</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>

`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("index").Parse(`

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Gitus</title>
	<link rel="stylesheet" href="/static/style.css">
  </head>
  <body>
	<div class="index-header">
	  <div class="index-header-label">DEPOT</div>
      <h1 class="index-header-name">Gitus</h1>
	</div>
    <hr />
	<table>
	  <thead>
		<tr>
		  <th>Repository</th>
		  <th>Description</th>
		</tr>
	  </thead>
	  <tbody>
		{{range .RepositoryList}}
		<tr>
		  <td><a href="/repo/{{.RelPath}}">{{.RelPath}}</a></td>
		  <td>{{.Description}}</td>
		</tr>
		{{end}}
	  </tbody>
    </table>
    <hr />
	<footer>
	  {{template "_footer"}}
	</footer>
  </body>
</html>
`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("internal-error").Parse(`

{{$reponame := .RepoName}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title></title>
	<link rel="stylesheet" href="/static/style.css">
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / ERROR</div>
      <h1 class="repo-header-name">{{.ErrorCode}}</h1>
	</div>
	<div class="repo-description"></div>
    <hr />

	<div class="error-message">{{.ErrorMessage}}</div>

	<hr />
	<footer>
	  <a href="/">Back to Depot</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>


`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("not-found").Parse(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>404 Not Found</title>
	<link rel="stylesheet" href="/static/style.css">
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / ERROR</div>
      <h1 class="repo-header-name">404</h1>
	</div>
	<div class="repo-description"></div>
    <hr />

	<div class="error-message">
	  <p>My friend, --<br />
		Whatever you're trying to find,<br />
		It's not here.<br />
	    Maybe, could be,<br />
	    Another time, another day.</p>
	</div>

	<hr />
	<footer>
	  <a href="/">Back to Depot</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>


`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("object").Parse(`{{$objid := .ObjectId}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </hed>
  <body>
    <h1>DirectlyAccessibleObject <code>{{$objid}}</code></h1>
	<h2>{{.ObjectType}}</h2>
    <pre>{{.ObjectData}}</pre>
    <hr />
    <a href="/">Back</a>
  </body>
</html>
`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("repository-not-found").Parse(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
	<link rel="stylesheet" href="/static/style.css">
  </hed>
  <body>
    <h1>Repository not found</h1>
    <p>Repository <code>{{.RepositoryName}}</code> not found.</p>
    <hr />
    <a href="/">Back</a>
  </body>
</html>
`)
  if err != nil { log.Fatal(err) }
  _, err = masterTemplate.New("repository").Parse(`

{{$reponame := .RepoName}}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title></title>
	<link rel="stylesheet" href="/static/style.css">
  </head>
  <body>
	<div class="repo-header">
	  <div class="repo-header-label"><a href="/">DEPOT</a> / REPOSITORY</div>
      <h1 class="repo-header-name">{{.RepoName}}</h1>
	</div>
	<div class="repo-description">{{.RepoObj.Description}}</div>
    <hr />

	<h2>Branches</h2>
	<ul>
	  {{range .BranchList}}
	  <li><a href="/repo/{{$reponame}}/branch/{{.Name}}">{{.Name}}</a></li>
	  {{end}}
	</ul>

	<h2>Tags</h2>
	<ul>
	  {{range .TagList}}
	  <li><a href="/repo/{{$reponame}}/tag/{{.Name}}">{{.Name}}</a></li>
	  {{end}}
	</ul>
	<hr />
	<footer>
	  <a href="/">Back to Depot</a>
	  {{template "_footer"}}
	</footer>
  </body>
</html>


`)
  if err != nil { log.Fatal(err) }

  return masterTemplate
}
