* operation mode


| mode   | namespace             | visibility                                      |
|--------+-----------------------+-------------------------------------------------|
| plain  | config ~useNamespace~ | config ~ignoreNamespace~ and ~ignoreRepository~ |
| simple | config ~useNamespace~ | special repo                                    |
| normal | config ~useNamespace~ | db-stored acl                                   |


| mode   | allow push | repo-level perm. | branch-level perm. | webui acl config |
|--------+------------+------------------+--------------------+------------------|
| plain  | no         | no               | no                 | no               |
| simple | yes        | yes              | planned*           | no               |
| normal | yes        | yes              | planned*           | yes              |

*: currently not implemented but there are plans to implement it

| mode   | user management | user management webui | description                |
|--------+-----------------+-----------------------+----------------------------|
| plain  | not applicable  | not applicable        | "read-only" for everyone   |
| simple | special repo    | no                    | for solodev or small teams |
| normal | db              | yes                   | for nearly any usage       |

** plain mode

setting a aegis instance to be in plain mode will completely remove all the functionalities that isn't built-in to git; this includes things like issue tracking and signature verification. in plain mode, gitus is basically like git instaweb.

** simple mode

this works similar to using gitolite.

under simple mode, two special repositories would be used:

+ ~__aegis:__keys~ (~__keys~ when ~useNamespace~ is false): repository for ssh and gpg keys.
+ ~__aegis:__repo_config~ (~__repo_config~ when ~useNamespace~ is false): repository for repo definitions and configs.

*** ~__keys~

the directory structure of this repo must be as follows:

#+begin_example
+ [username1]
  + ssh
    + [user1.pubkey1.name]
    + [user1.pubkey2.name]
    + ...
  + gpg
    + [user1.gpgkey1.name]
    + [user1.gpgkey2.name}
    + ...
+ [username2]
  + ssh
    + [user2.pubkey1.name]
    + [user2.pubkey2.name]
    + ...
  + gpg
    + [user2.gpgkey1.name]
    + [user2.gpgkey2.name}
    + ...
+ ...
#+end_example

the ~update~ hook of this repo is configured to trigger command ~aegis simple-mode update-keys~, which will generate the required ~authorized_keys~ file accordingly.

*** ~__repo_config~

the directory structure of this repo must be as follows:

#+begin_example
+ [namespace1]
  + [reponame1]
    + config.mdconf
  + [reponame2]
    + config.mdconf
  + ...
+ [namespace2]
  + [reponame1]
  + [reponame2]
  + ...
+ ...
#+end_example

if useNamespace is false, then the structure would be:

#+begin_example
  + [reponame1]
    + config.mdconf
  + [reponame2]
    + config.mdconf
  + ...
#+end_example

the ~.mdconf~ are mdconf files of the following format:

#+begin_src markdown
  # repo
  + description: [repo description]
  + visibility: [visibility;("public" or "private")]

  ## hooks
  + [hookname]: [filename;(resolved against location of config.mdconf)]
  + [hookname]: [filename;(resolved against location of config.mdconf)]
  // ...

  ## users
  ### [username1]
  + 


#+end_src

